alias npmp='npm publish'
alias npma='npm adduser'
alias npmi='npm install'
alias npmg='npm install -g'
alias npmu='npm update'
alias npmr='npm uninstall'
alias npmrg='npm uninstall -g'
alias nis='npm install --save '
alias nisd='npm install --save-dev '

alias p='pnpm '
alias pi='pnpm i'
alias pd='pnpm dev'
alias pb='pnpm build'
alias px='pnpm dlx'
alias pe='pnpm exec'
alias ncu='npx npm-check-updates -u'
alias bi='bun i'
alias bd='bun dev'

alias brewd='brew doctor'
alias brewi='brew install'
alias brewr='brew uninstall'
alias brews='brew search'
alias brewu='brew update --quiet && brew upgrade && brew cleanup'
alias update='sudo softwareupdate --install --all && brew update && brew upgrade && brew cleanup'
