# Added by OrbStack: command-line tools and integration
[[ -f "$HOME/.orbstack/shell/init.zsh" ]] && source "$HOME/.orbstack/shell/init.zsh"

[ -r "$HOME/.zprofile.local" ] && source "$HOME/.zprofile.local"
