for file in ~/.{extra,exports,aliases,functions,colors}; do
    [ -r "$file" ] && source "$file"
done
unset file

# macOS: Homebrew setup
if [[ "$OSTYPE" == "darwin"* ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

eval "$(starship init zsh)"
eval "$(sheldon source)"
